export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/index.html.js"), meta: {"title":"巅峰世界","icon":"house"} }],
  ["/docs/advanced-search.html", { loader: () => import(/* webpackChunkName: "docs_advanced-search.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/advanced-search.html.js"), meta: {"date":1764341183000,"excerpt":"<p>这里是巅峰世界百科的 <strong>高级搜索</strong>。你可以根据「人物 / 城市 / 组织 / 概念」等分类来筛选结果。</p>\n","readingTime":{"minutes":0.16,"words":49},"title":"高级搜索","icon":"search","type":"article"} }],
  ["/docs/characterline.html", { loader: () => import(/* webpackChunkName: "docs_characterline.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/characterline.html.js"), meta: {"date":1759760065000,"excerpt":"<h2>人物关系图谱</h2>\n","readingTime":{"minutes":0.19,"words":56},"title":"人物关系图谱","type":"article"} }],
  ["/docs/hotpages.html", { loader: () => import(/* webpackChunkName: "docs_hotpages.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/hotpages.html.js"), meta: {"date":1764398930000,"readingTime":{"minutes":0.08,"words":25},"title":"推荐文章","type":"article"} }],
  ["/docs/", { loader: () => import(/* webpackChunkName: "docs_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/index.html.js"), meta: {"title":"世界观总览","icon":"laptop-code"} }],
  ["/docs/RoleCard.html", { loader: () => import(/* webpackChunkName: "docs_RoleCard.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/RoleCard.html.js"), meta: {"date":1759711076000,"excerpt":"<div class=\"role-grid\">\n  <!-- 1. 灵动骑士（简版） -->\n  </div>\n","readingTime":{"minutes":1,"words":300},"title":"关系卡","type":"article"} }],
  ["/docs/timeline.html", { loader: () => import(/* webpackChunkName: "docs_timeline.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/timeline.html.js"), meta: {"date":1759756071000,"readingTime":{"minutes":0.29,"words":86},"title":"世界大事年表","type":"article"} }],
  ["/docs/worldmap.html", { loader: () => import(/* webpackChunkName: "docs_worldmap.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/worldmap.html.js"), meta: {"date":1759644953000,"readingTime":{"minutes":0.23,"words":70},"title":"世界地图","type":"article"} }],
  ["/docs/world/characters/", { loader: () => import(/* webpackChunkName: "docs_world_characters_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/index.html.js"), meta: {"title":"角色介绍","icon":"user"} }],
  ["/docs/world/geography/", { loader: () => import(/* webpackChunkName: "docs_world_geography_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/geography/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/concepts/", { loader: () => import(/* webpackChunkName: "docs_world_concepts_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/concepts/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/", { loader: () => import(/* webpackChunkName: "docs_world_factions_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/characters/CCO/", { loader: () => import(/* webpackChunkName: "docs_world_characters_CCO_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/CCO/index.html.js"), meta: {"date":1759711076000,"title":"","type":"article"} }],
  ["/docs/world/history/", { loader: () => import(/* webpackChunkName: "docs_world_history_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/history/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/characters/divineproxy/", { loader: () => import(/* webpackChunkName: "docs_world_characters_divineproxy_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/divineproxy/index.html.js"), meta: {"date":1759711076000,"title":"","type":"article"} }],
  ["/docs/world/power/", { loader: () => import(/* webpackChunkName: "docs_world_power_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/power/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/characters/superhero/character-EtherealKnight.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-EtherealKnight.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-EtherealKnight.html.js"), meta: {"date":1759636241000,"category":["人类","英雄","异能者"],"tag":["灵动骑士","世界英雄"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<figure><img src=\"/images/EtherealKnightCombatSuit.jpg\" alt=\"宇文南城001\" width=\"180\" tabindex=\"0\" loading=\"lazy\"><figcaption>宇文南城001</figcaption></figure>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":9.37,"words":2810},"title":"灵动骑士","type":"article"} }],
  ["/docs/world/characters/superhero/character-HearTone.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-HearTone.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-HearTone.html.js"), meta: {"date":1759644953000,"category":["人类","英雄","魔法少女","神明代理"],"tag":["世界英雄","魔法少女","神明代理"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":0.54,"words":161},"title":"赤听","type":"article"} }],
  ["/docs/world/characters/superhero/character-Illustra.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-Illustra.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-Illustra.html.js"), meta: {"date":1759711076000,"category":["人类","英雄","异能者"],"tag":["世界英雄"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":0.44,"words":131},"title":"幻绘星","type":"article"} }],
  ["/docs/world/characters/superhero/character-M-A-Y.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-M-A-Y.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-M-A-Y.html.js"), meta: {"date":1759711076000,"category":["人类","英雄","异能者"],"tag":["世界英雄"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":0.42,"words":126},"title":"月五","type":"article"} }],
  ["/docs/world/characters/superhero/character-Scourge.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-Scourge.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-Scourge.html.js"), meta: {"date":1759636241000,"excerpt":"\n<h2>基本信息</h2>\n<hr>\n","readingTime":{"minutes":2.36,"words":707},"title":"天灾","type":"article"} }],
  ["/docs/world/characters/superhero/character-StrikeClock.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-StrikeClock.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-StrikeClock.html.js"), meta: {"date":1759711076000,"category":["人类","英雄","黑科技使用者"],"tag":["世界英雄"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":0.45,"words":136},"title":"警钟","type":"article"} }],
  ["/docs/world/characters/superhero/character-WizardHope.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_character-WizardHope.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/character-WizardHope.html.js"), meta: {"date":1759711076000,"category":["人类","英雄","魔法师"],"tag":["世界英雄"],"isOriginal":true,"excerpt":"<div class=\"ai-row\">\n</div>\n<h1>基本信息</h1>\n<hr>\n","readingTime":{"minutes":0.42,"words":127},"title":"巫师希望","type":"article"} }],
  ["/docs/world/characters/superhero/", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/index.html.js"), meta: {"date":1759636241000,"excerpt":"<p>这里可以写一点团体的文字介绍。<br>\n比如巅峰议会的成立历史、议会目标、对世界格局的影响等等。</p>\n<p>下面也可以继续正常写 Markdown 内容：</p>\n<ul>\n<li>组织结构</li>\n<li>议会会议制度</li>\n<li>与各团体的关系</li>\n<li><a href=\"/docs/world/characters/superhero/character-EtherealKnight.html\" target=\"_blank\">灵动骑士</a></li>\n<li><a href=\"/docs/world/characters/superhero/character-Scourge.html\" target=\"_blank\">天灾</a></li>\n<li><a href=\"/docs/world/characters/superhero/character-HearTone.html\" target=\"_blank\">HearTone</a></li>\n<li><a href=\"/docs/world/characters/superhero/character-M-A-Y.html\" target=\"_blank\">M·A·Y</a></li>\n<li><a href=\"/docs/world/characters/superhero/test-b.html\" target=\"_blank\">测试页面</a></li>\n<li>……把你所有角色都列上来</li>\n</ul>","readingTime":{"minutes":1.64,"words":493},"title":"超级英雄","type":"article"} }],
  ["/docs/world/characters/superhero/test-a.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_test-a.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/test-a.html.js"), meta: {"date":1764636538000,"excerpt":"<p>这是测试目标 A 的页面。</p>\n","readingTime":{"minutes":0.05,"words":16},"title":"测试目标A","type":"article"} }],
  ["/docs/world/characters/superhero/test-b.html", { loader: () => import(/* webpackChunkName: "docs_world_characters_superhero_test-b.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/characters/superhero/test-b.html.js"), meta: {"date":1764636538000,"excerpt":"<p>我在这里随便写一句：测试目标A会不会被自动加链接。</p>\n","readingTime":{"minutes":0.09,"words":27},"title":"测试 B","type":"article"} }],
  ["/docs/world/concepts/twelveprimedeities/", { loader: () => import(/* webpackChunkName: "docs_world_concepts_twelveprimedeities_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/concepts/twelveprimedeities/index.html.js"), meta: {"date":1763552885000,"tag":["神明"],"isOriginal":true,"excerpt":"<p>十二主神是所有神话都存在的十二种权能，每当时代更替，将会出现新的神话，将会出现新的十二主神。</p>\n<blockquote>\n<p>——新的神明即将降临。</p>\n</blockquote>\n<h1>十二主神</h1>\n<p>－ 天神/全能神/主神<br>\n－ 太阳神/光明神<br>\n－ 月神/黑夜神<br>\n－ 战争之神<br>\n－ 大地神/母神/生命神<br>\n－ 风暴神/雷神<br>\n－ 爱神/美神<br>\n－</p>\n<h1>十二主神的由来</h1>\n<p>十二主神并不是严格遵守十二这个数字，实际上，并没有完全遵守十二这个数字的神话体系，十二主神，只是被某位神学家整理出来的，在各个神话体系中出现频率最高的神职，虽然谁也没见过神明的诞生，但是据他研究，神明的诞生于这些神职之中，至于是被赋予，还是经由争夺，这就不得而知了。<br>\n有的神系将神职聚于一身，成为唯一神系；有的神系则贴近十二主神的分工，平衡而和谐；而有的神系，不断地将神职分裂，最终塑造了万物皆神的体系。这些神系虽然各有各的架构，但是也各有各的强，并不能粗浅的将其分个强弱。</p>","readingTime":{"minutes":1.15,"words":344},"title":"十二主神","type":"article"} }],
  ["/docs/world/concepts/isomer/", { loader: () => import(/* webpackChunkName: "docs_world_concepts_isomer_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/concepts/isomer/index.html.js"), meta: {"date":1763614134000,"excerpt":"<p>名称：异常构造<br>\n译名：Isomer<br>\n简称：异构、ISO</p>\n<h2>关于「异常构造」的详细定义</h2>\n<p>在这个世界，即便存在大量离奇事物，【异常构造】仍是其中最特殊且最危险的一类。</p>\n<h3>旧定义</h3>\n<p>在危机管理机构时期，最初的定义是：</p>\n<blockquote>\n<p>“以极不合理的机制运行的事物。”</p>\n</blockquote>\n<p>问题在于，这个定义过于宽泛，导致许多“只是难以理解但不算异常”的现象也被划入该类。</p>\n<h3>新定义</h3>\n<p>某位博士提出了一个颠覆性的理论：【异常构造】的本质，是对【宇宙本源】的消耗行为。<br>\n关于【宇宙本源】的性质，他给了一个可理解的类比：</p>","readingTime":{"minutes":2.95,"words":886},"title":"异常构造","type":"article"} }],
  ["/docs/world/factions/heroic/", { loader: () => import(/* webpackChunkName: "docs_world_factions_heroic_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/heroic/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/neutral/", { loader: () => import(/* webpackChunkName: "docs_world_factions_neutral_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/neutral/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/official/", { loader: () => import(/* webpackChunkName: "docs_world_factions_official_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/official/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/others/", { loader: () => import(/* webpackChunkName: "docs_world_factions_others_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/others/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/villainous/", { loader: () => import(/* webpackChunkName: "docs_world_factions_villainous_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/villainous/index.html.js"), meta: {"date":1763552885000,"title":"","type":"article"} }],
  ["/docs/world/factions/official/AMA/", { loader: () => import(/* webpackChunkName: "docs_world_factions_official_AMA_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/factions/official/AMA/index.html.js"), meta: {"date":1763552885000,"category":["组织","官方"],"tag":["国际"],"excerpt":"<p>名称：异常事物管理局<br>\n译名：Anomaly Management Agency<br>\n简称：AMA<br>\n成立日期：</p>\n<h2>历史</h2>\n<p>异常管理局的源头可追溯至【先知】创立的早期组织——【危机管理机构】(Crisis Control Organization，简称C.C.O.)。当【巅峰议会】正式成立后，危机管理机构内部负责关押、限制和控制超自然事物的部门被独立出来，成为【危机控制局】，职能类似超自然收容所或监狱。余下专司调查、管理与应对异常现象的人员与部门，则整编为最初的【异常管理局】(Anomaly Management Agency，简称A.M.A.)。<br>\n随着时间推移，异常管理局依据全球超自然事物的规模、分布与特征，将其划分为十三大类，并设立对应的十三个分局分别负责各自的领域。其总职能可概括为四项：</p>","readingTime":{"minutes":3.13,"words":939},"title":"异常事物管理局","icon":"iconoir:book","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/docs/world/", { loader: () => import(/* webpackChunkName: "docs_world_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/docs/world/index.html.js"), meta: {"title":"World"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E4%BA%BA%E7%B1%BB/", { loader: () => import(/* webpackChunkName: "category_人类_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/人类/index.html.js"), meta: {"title":"人类 分类","index":false} }],
  ["/category/%E8%8B%B1%E9%9B%84/", { loader: () => import(/* webpackChunkName: "category_英雄_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/英雄/index.html.js"), meta: {"title":"英雄 分类","index":false} }],
  ["/category/%E5%BC%82%E8%83%BD%E8%80%85/", { loader: () => import(/* webpackChunkName: "category_异能者_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/异能者/index.html.js"), meta: {"title":"异能者 分类","index":false} }],
  ["/category/%E9%AD%94%E6%B3%95%E5%B0%91%E5%A5%B3/", { loader: () => import(/* webpackChunkName: "category_魔法少女_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/魔法少女/index.html.js"), meta: {"title":"魔法少女 分类","index":false} }],
  ["/category/%E7%A5%9E%E6%98%8E%E4%BB%A3%E7%90%86/", { loader: () => import(/* webpackChunkName: "category_神明代理_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/神明代理/index.html.js"), meta: {"title":"神明代理 分类","index":false} }],
  ["/category/%E9%BB%91%E7%A7%91%E6%8A%80%E4%BD%BF%E7%94%A8%E8%80%85/", { loader: () => import(/* webpackChunkName: "category_黑科技使用者_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/黑科技使用者/index.html.js"), meta: {"title":"黑科技使用者 分类","index":false} }],
  ["/category/%E9%AD%94%E6%B3%95%E5%B8%88/", { loader: () => import(/* webpackChunkName: "category_魔法师_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/魔法师/index.html.js"), meta: {"title":"魔法师 分类","index":false} }],
  ["/category/%E7%BB%84%E7%BB%87/", { loader: () => import(/* webpackChunkName: "category_组织_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/组织/index.html.js"), meta: {"title":"组织 分类","index":false} }],
  ["/category/%E5%AE%98%E6%96%B9/", { loader: () => import(/* webpackChunkName: "category_官方_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/category/官方/index.html.js"), meta: {"title":"官方 分类","index":false} }],
  ["/en/category/", { loader: () => import(/* webpackChunkName: "en_category_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/en/category/index.html.js"), meta: {"title":"Category","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E7%81%B5%E5%8A%A8%E9%AA%91%E5%A3%AB/", { loader: () => import(/* webpackChunkName: "tag_灵动骑士_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/灵动骑士/index.html.js"), meta: {"title":"标签: 灵动骑士","index":false} }],
  ["/tag/%E4%B8%96%E7%95%8C%E8%8B%B1%E9%9B%84/", { loader: () => import(/* webpackChunkName: "tag_世界英雄_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/世界英雄/index.html.js"), meta: {"title":"标签: 世界英雄","index":false} }],
  ["/tag/%E9%AD%94%E6%B3%95%E5%B0%91%E5%A5%B3/", { loader: () => import(/* webpackChunkName: "tag_魔法少女_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/魔法少女/index.html.js"), meta: {"title":"标签: 魔法少女","index":false} }],
  ["/tag/%E7%A5%9E%E6%98%8E%E4%BB%A3%E7%90%86/", { loader: () => import(/* webpackChunkName: "tag_神明代理_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/神明代理/index.html.js"), meta: {"title":"标签: 神明代理","index":false} }],
  ["/tag/%E7%A5%9E%E6%98%8E/", { loader: () => import(/* webpackChunkName: "tag_神明_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/神明/index.html.js"), meta: {"title":"标签: 神明","index":false} }],
  ["/tag/%E5%9B%BD%E9%99%85/", { loader: () => import(/* webpackChunkName: "tag_国际_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/tag/国际/index.html.js"), meta: {"title":"标签: 国际","index":false} }],
  ["/en/tag/", { loader: () => import(/* webpackChunkName: "en_tag_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/en/tag/index.html.js"), meta: {"title":"Tag","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/en/article/", { loader: () => import(/* webpackChunkName: "en_article_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/en/article/index.html.js"), meta: {"title":"Articles","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/en/star/", { loader: () => import(/* webpackChunkName: "en_star_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/en/star/index.html.js"), meta: {"title":"Star","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
  ["/en/timeline/", { loader: () => import(/* webpackChunkName: "en_timeline_index.html" */"C:/Users/super/ZenithWorld/wiki/.vuepress/.temp/pages/en/timeline/index.html.js"), meta: {"title":"Timeline","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
